---
- name: restart atop service
  service:
    name: atop
    state: restarted

- name: reload atop unit
  systemd:
    daemon_reload: yes

- name: restart atop services
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - atop.service
    - atop-rotate.service
    - atop-rotate.timer

- name: restart cron service from atop
  systemd:
    name: cron
    state: restarted
